---
sudo: required

env:
  - distribution: ubuntu
    version: 12.04
    init: /sbin/init
    run_opts: ""
    playbook: test.yml
  - distribution: ubuntu
    version: 14.04
    init: /sbin/init
    run_opts: ""
    playbook: test.yml
  - distribution: ubuntu
    version: 16.04
    init: /sbin/init
    run_opts: ""
    playbook: test.yml


# whitelist
branches:
  only:
    - master

before_install:
 - sudo apt-add-repository ppa:ansible/ansible -y
 - sudo apt-get update -qq
 - sudo apt-get install -qq ansible

script:
 # Prepare tests
  - echo localhost > inventory

  # Check syntax
  - ansible-playbook --syntax-check -i inventory test.yml

  # First run
  - ansible-playbook -i inventory test.yml --connection=local --sudo

  # Second run Idempotence test
  - >
    ansible-playbook -i inventory test.yml --connection=local --sudo
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)

  - ps -ef | grep /usr/lib/postfix | grep -v grep || exit 1
